services:

  postgres:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    volumes:
      - postgres_data_test:/var/lib/postgresql/data

  django:
    container_name: django
    build:
      context: ./
    env_file:
      - ./.env
    environment:
      WEBAPP_ROOT_URL: http://127.0.0.1:8000
      POSTGRES_DSN: postgres://postgres_user:postgres_password@postgres:5432/postgres_db
      DJ__SECRET_KEY: empty
      DJ__DEBUG: 'true'
      DJ__ALLOWED_HOSTS: '127.0.0.1, localhost, .ngrok-free.app'
      DJ__CSRF_TRUSTED_ORIGINS: 'https://*.ngrok-free.app'
      ENABLE_DEBUG_TOOLBAR: 'true'
      ENABLE_MEDIA_FILES_SERVING: 'true'
      GUNICORN_CMD_ARGS: '--reload --workers 2'
    ports:
      - 127.0.0.1:8000:80
    volumes:
      - ./media:/media/
      - ./src:/opt/app/src/
      - ./pyproject.toml:/opt/app/pyproject.toml
      - ./poetry.lock:/opt/app/poetry.lock
    depends_on:
      - postgres
    command: >
      sh -c "
      python /opt/app/src/manage.py migrate "

volumes:
  postgres_data_test:
