# Generated by Django 5.1.2 on 2024-11-05 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_alter_module_drugs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="speakers",
            field=models.ManyToManyField(
                blank=True, related_name="modules", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
