# Generated by Django 5.1.2 on 2024-11-05 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_alter_file_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="drugs",
            field=models.ManyToManyField(
                blank=True,
                related_name="courses",
                to="course.drug",
                verbose_name="Препараты",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="lecturers",
            field=models.ManyToManyField(
                blank=True,
                related_name="courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Лекторы",
            ),
        ),
    ]
