# Generated by Django 5.1.2 on 2024-11-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_alter_modulecompletion_module_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="drug",
            name="public",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Доступно всем"
            ),
        ),
    ]
